version: "2"
services:
  redis:
    image: redis:3.2-alpine
  job:
    build: job/
    image: so0k/coreos-updatenotice
    # tty: true
    # stdin_open: true
    # command: /bin/sh
    environment:
      - WEBHOOK_URL=http://test-webhook:5000/echo
      - COREOS_CHANNELS=stable,alpha
    depends_on: 
      - redis
      - test-webhook
  test-webhook:
    build: echo-server/
    image: so0k/echo-server
      
