apiVersion: v1
kind: Service
metadata:
  name: coreos-updatenotice-redis
  labels:
    app: coreos-updatenotice-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: coreos-updatenotice-redis
