apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coreos-updatenotice-redis
  labels:
    app: coreos-updatenotice-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreos-updatenotice-redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: coreos-updatenotice-redis
    spec:
      containers:
      - image: redis:3.2-alpine
        name: coreos-updatenotice-redis
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
